# Generated by Django 5.0.3 on 2024-03-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredientrelation",
            old_name="ingredient",
            new_name="ingredient_id",
        ),
        migrations.RenameField(
            model_name="recipeingredientrelation",
            old_name="recipe",
            new_name="recipe_id",
        ),
    ]
