# Generated by Django 5.0.3 on 2024-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe", name="serving", field=models.CharField(max_length=50),
        ),
    ]
