# Generated by Django 5.0.3 on 2024-05-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipe",
            "0002_rename_ingredient_recipeingredientrelation_ingredient_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="recipe", name="cluster",),
        migrations.RemoveField(model_name="recipe", name="ingredients_with_quantity",),
        migrations.RemoveField(model_name="recipe", name="tag",),
    ]
