# Generated by Django 5.0.3 on 2024-03-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recipe",
            "0002_rename_ingredient_recipeingredientrelation_ingredient_id_and_more",
        ),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="like",
            field=models.ManyToManyField(through="user.Likes", to="recipe.recipe"),
        ),
    ]
